name: Node Build
on:
  push:
    paths:
      - 'node/code/**'
      - '.github/workflows/build_node.yml'
    branches:
      - main
      - node_ci
  pull_request:
    paths:
      - 'node/code/**'
      - '.github/workflows/build_node.yml'
    branches:
      - main
      - node_ci

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Build Node
        run: |
          cd node/code
          BUILD_IN_DOCKER=1 make all

